# fly.toml app configuration file generated for pasada-backend on 2025-05-05T06:30:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pasada-backend"
primary_region = "sin"

[build]
builder = "heroku/builder:24"

[env]
NODE_ENV = "production"
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

